In [1]:
import diamond

In [2]:
import numpy as np
import scipy as sp
import pygsti 

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('white')
%matplotlib inline

In [43]:
sigI = np.array([[1.,0],[0, 1]], dtype='complex')
sigX = np.array([[0, 1],[1, 0]], dtype='complex')
sigY = np.array([[0,-1],[1, 0]], dtype='complex') * 1.j
sigZ = np.array([[1, 0],[0,-1]], dtype='complex')
sigM = (sigX - 1.j*sigY)/2.
sigP = (sigX + 1.j*sigY)/2.
def x(theta):
    return sp.linalg.expm(-1.j*(np.pi/2 + theta)*sigX)

In [9]:
def x(theta):
    return np.exp(-1.j*(np.pi/2 + theta)*sigX)
def superop(unitary):
    return np.kron(unitary.conj(), unitary)

In [49]:
x(.1)

array([[-0.09983342-0.j        ,  0.        -0.99500417j],
       [ 0.        -0.99500417j, -0.09983342-0.j        ]])

In [51]:
4*entFid

(0.9900332889206208+0j)

In [56]:
theta = 0.042
diamond_dist = diamond.diamond_norm(diamond.jamiolkowski(superop(x(0))) - diamond.jamiolkowski(superop(x(theta))))/(2)
diamond_dist_avg = diamond.diamond_norm(diamond.jamiolkowski(superop(x(0))) - diamond.jamiolkowski(superop(x(theta))/2.+superop(x(-theta))/2.))/(2)
print(theta, diamond_dist)
print(theta**2, diamond_dist_avg)
entFid = np.trace(np.dot(diamond.jamiolkowski(superop(x(0))),diamond.jamiolkowski(superop(x(theta)))))/4
entFid_avg = np.trace(np.dot(diamond.jamiolkowski(superop(x(0))),
                             diamond.jamiolkowski(superop(x(theta)))/2. + diamond.jamiolkowski(superop(x(-theta)))/2.))/4
print(theta**2, 1-entFid)
print(theta**2, 1-entFid_avg)

0.042 0.04198765252168646
0.0017640000000000002 0.001762962993716387
0.0017640000000000002 (0.001762963011926355+0j)
0.0017640000000000002 (0.001762963011926244+0j)


In [20]:
diamond.jamiolkowski(superop(x(0)))

array([[1.000000e+00+0.j, 6.123234e-17+1.j, 6.123234e-17+1.j,
        1.000000e+00+0.j],
       [6.123234e-17-1.j, 1.000000e+00+0.j, 1.000000e+00+0.j,
        6.123234e-17-1.j],
       [6.123234e-17-1.j, 1.000000e+00+0.j, 1.000000e+00+0.j,
        6.123234e-17-1.j],
       [1.000000e+00+0.j, 6.123234e-17+1.j, 6.123234e-17+1.j,
        1.000000e+00+0.j]])

In [10]:
diamondsuperop(x(0.1))

array([[ 1.        +0.j        , -0.09983342-0.99500417j,
        -0.09983342+0.99500417j,  1.        +0.j        ],
       [-0.09983342-0.99500417j,  1.        +0.j        ,
         1.        +0.j        , -0.09983342+0.99500417j],
       [-0.09983342+0.99500417j,  1.        +0.j        ,
         1.        +0.j        , -0.09983342-0.99500417j],
       [ 1.        +0.j        , -0.09983342+0.99500417j,
        -0.09983342-0.99500417j,  1.        +0.j        ]])

In [ ]:
from import diamond_norm, jamiolkowski

def superoperator(unitary):
    return np.kron(unitary.conj(), unitary)

def choi_form(unitary):
    return jamiolkowski(superoperator(unitary))

def diamond_distance(unitary_a,unitary_b):
    return diamond_norm(choi_form(unitary_a) - choi_form(unitary_b))/2.

def entanglement_infidelity(unitary_a,unitary_b):
    dim = len(unitary_a)
    return 1 - np.trace( np.dot(choi_form(unitary_a), choi_form(unitary_b)))/(4**dim)
    